### PR TITLE
Add Downstream buildview Job's Grey Ball blinking as optional

### PR DESCRIPTION
**Pull request by mahi8061**
Description : 
Add Downstream buildview Job's Grey Ball blinking as an optional feature. 
Global configuration is added so that user can set Downstream job's Grey ball blinking option to On/Off.
By default this option is disabled so that no change in the existing behavior of this plugin until and unless user selects the global blinking option.

Please Review!
Thanks.

### CODE REVIEW

**Comment by rpetti** [comment]
Why would you want to disable the blinking balls? That's your only indication that the job is building, and turning it off breaks consistency with the rest of the application.

**Comment by mahi8061** [comment]
In our case, There are some downstream jobs which will never be triggered if some condition fails. 
When we are looking for the status of those jobs, they are blinking forever with status as NOT BUILT. It gives us an illusion that downstream jobs are still not triggered which is true but the blinking will be permanent for those jobs. In our case, blinking shouldn't be there for those jobs which won't be triggered.

**Comment by rpetti** [comment]
It should only be blinking when the build is actually running. Having a global option that completely disables blinking balls seems like the wrong solution here.

**Comment by rpetti** [comment]
I've provided an alternative solution to the described problem in #9.

**Comment by mahi8061** [comment]
In my change, as the text like "build number 73 (2.7 sec and counting) " also tells the status of the job that is running.

**Comment by mahi8061** [comment]
Changed as per @rpetti comment.

**Comment by mahi8061** [comment]
Hello @rpetti ,
Could you please merge this patch? 
We want to use this in our Jenkins.
Thanks!

**Comment by rpetti** [comment]
I don't have the ability to merge it, unfortunately, that's why I filed my own pull request instead of just committing directly.
The plugin appears to be unmaintained and is up for adoption, so if you'd like to merge either PR, you should request access:
https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin

**Comment by mahi8061** [comment]
Okay thanks! @rpetti

**Pull request closed without merging**
